name: Python Application CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s tests

    - name: Deploy to Azure Web App (Optional)
      env:
        AZURE_WEBAPP_NAME: 'WebApp-Code-Python-Linux'  # Replace with your Azure Web App name
        AZURE_WEBAPP_PACKAGE_PATH: '.'  # Update this if your project is not at the root
        PYTHON_VERSION: '3.9'  # Use the version that matches your app's runtime

      run: |
        echo "Deploying to Azure Web App..."
        # Add your deployment steps here, for example using Azure CLI or other tools
